# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/js/Documents/OpenGL-GLFW-Template

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/js/Documents/OpenGL-GLFW-Template

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/js/Documents/OpenGL-GLFW-Template/CMakeFiles /home/js/Documents/OpenGL-GLFW-Template//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/js/Documents/OpenGL-GLFW-Template/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gl3w

# Build rule for target.
gl3w: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gl3w
.PHONY : gl3w

# fast build rule for target.
gl3w/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gl3w.dir/build.make CMakeFiles/gl3w.dir/build
.PHONY : gl3w/fast

#=============================================================================
# Target rules for targets named GL_GLFW_TEMPLATE

# Build rule for target.
GL_GLFW_TEMPLATE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GL_GLFW_TEMPLATE
.PHONY : GL_GLFW_TEMPLATE

# fast build rule for target.
GL_GLFW_TEMPLATE/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GL_GLFW_TEMPLATE.dir/build.make CMakeFiles/GL_GLFW_TEMPLATE.dir/build
.PHONY : GL_GLFW_TEMPLATE/fast

includes/GL/src/gl3w.o: includes/GL/src/gl3w.c.o

.PHONY : includes/GL/src/gl3w.o

# target to build an object file
includes/GL/src/gl3w.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gl3w.dir/build.make CMakeFiles/gl3w.dir/includes/GL/src/gl3w.c.o
.PHONY : includes/GL/src/gl3w.c.o

includes/GL/src/gl3w.i: includes/GL/src/gl3w.c.i

.PHONY : includes/GL/src/gl3w.i

# target to preprocess a source file
includes/GL/src/gl3w.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gl3w.dir/build.make CMakeFiles/gl3w.dir/includes/GL/src/gl3w.c.i
.PHONY : includes/GL/src/gl3w.c.i

includes/GL/src/gl3w.s: includes/GL/src/gl3w.c.s

.PHONY : includes/GL/src/gl3w.s

# target to generate assembly for a file
includes/GL/src/gl3w.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gl3w.dir/build.make CMakeFiles/gl3w.dir/includes/GL/src/gl3w.c.s
.PHONY : includes/GL/src/gl3w.c.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GL_GLFW_TEMPLATE.dir/build.make CMakeFiles/GL_GLFW_TEMPLATE.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GL_GLFW_TEMPLATE.dir/build.make CMakeFiles/GL_GLFW_TEMPLATE.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GL_GLFW_TEMPLATE.dir/build.make CMakeFiles/GL_GLFW_TEMPLATE.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/shader.o: src/shader.cpp.o

.PHONY : src/shader.o

# target to build an object file
src/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GL_GLFW_TEMPLATE.dir/build.make CMakeFiles/GL_GLFW_TEMPLATE.dir/src/shader.cpp.o
.PHONY : src/shader.cpp.o

src/shader.i: src/shader.cpp.i

.PHONY : src/shader.i

# target to preprocess a source file
src/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GL_GLFW_TEMPLATE.dir/build.make CMakeFiles/GL_GLFW_TEMPLATE.dir/src/shader.cpp.i
.PHONY : src/shader.cpp.i

src/shader.s: src/shader.cpp.s

.PHONY : src/shader.s

# target to generate assembly for a file
src/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GL_GLFW_TEMPLATE.dir/build.make CMakeFiles/GL_GLFW_TEMPLATE.dir/src/shader.cpp.s
.PHONY : src/shader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GL_GLFW_TEMPLATE"
	@echo "... gl3w"
	@echo "... includes/GL/src/gl3w.o"
	@echo "... includes/GL/src/gl3w.i"
	@echo "... includes/GL/src/gl3w.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/shader.o"
	@echo "... src/shader.i"
	@echo "... src/shader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

